name: furniture_movers_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl_phone_field: ^3.2.0
  carousel_slider: ^5.1.1
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.1.0
  otp_text_field: ^1.1.3
  pin_code_fields: ^8.0.1
  font_awesome_flutter: ^10.8.0
  url_launcher: ^6.2.5
  flutter_svg: ^2.2.0
  image_picker: ^1.1.2
  smooth_page_indicator: ^1.2.1
  provider: ^6.0.3
  intl: ^0.17.0
  dio: ^5.8.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai-Regular.ttf
          weight: 400
        - asset: assets/fonts/Almarai-Bold.ttf
          weight: 700
        - asset: assets/fonts/Almarai-ExtraBold.ttf
          weight: 800

    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-ExtraBold.ttf
          weight: 800

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
